/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design_panel;

import Entities.Product;
import Entities.Store;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jatt6
 */
public class Product_Portal extends javax.swing.JFrame {

    /**
     * Creates new form Product_Portal
     */
    public Product_Portal() {
        initComponents();
        this.setLocation(650,190);
        Store.addDummyProducts();
        setTableValues();
    }
     void setTableValues(){
    ArrayList<Product> products =Store.getAllProducts();
         if (products!=null) {
             
         
         DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
         for (int i = 0; i < products.size(); i++) {
             Object [] cols=new Object[6];
             cols[0]=products.get(i).getId();
             cols[1]=products.get(i).getName();
                cols[2]=products.get(i).getCategory();  
                
                   cols[3]=products.get(i).getStock();
                      cols[4]=products.get(i).getWsr();
                         cols[5]=products.get(i).getRetailp();
                         model.addRow(cols);
             
             
         }
         }
    
    
    }
     void setSingleTableValue(Product p){
   
        
             
         
         DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
      
             Object [] cols=new Object[6];
             cols[0]=p.getId();
             cols[1]=p.getName();
                cols[2]=p.getCategory();  
                
                   cols[3]=p.getStock();
                      cols[4]=p.getWsr();
                         cols[5]=p.getRetailp();
                         model.addRow(cols);
             
             
        
     
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prd_ID = new javax.swing.JTextField();
        wsRate = new javax.swing.JTextField();
        retailP = new javax.swing.JTextField();
        nameItem = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        category = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchBar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(790, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCT PORTAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 0, 340, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Product ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 59, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Category");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("WS Rate");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Retail Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 177, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Stock");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(prd_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 176, -1));
        getContentPane().add(wsRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 176, -1));
        getContentPane().add(retailP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 176, -1));
        getContentPane().add(nameItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 176, -1));
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, -1));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Fruits", "Snakcs", "Meat", "Others" }));
        getContentPane().add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 176, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 367, 55, -1));

        jButton2.setText("DEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 367, 55, -1));

        jButton3.setText("UPD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 367, 61, -1));

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 367, -1, -1));
        getContentPane().add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 56, 381, -1));

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 95, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Category", "Stock", "WSR", "RTP"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 130, 381, 328));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_panel/Background Images/Dashboard.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!prd_ID.getText().isEmpty()
            &&!category.getSelectedItem().toString().isEmpty()
               &&!wsRate.getText().isEmpty() 
                &&!retailP.getText().isEmpty()
                &&!nameItem.getText().isEmpty()
                &&!stock.getText().isEmpty()){
            Product p = new Product();
            p.setId(Integer.parseInt(prd_ID.getText()));
            p.setRetailp(Double.parseDouble(retailP.getText()));
            p.setWsr(Double.parseDouble(wsRate.getText()));
            p.setStock(Integer.parseInt(stock.getText()));
            p.setName(nameItem.getText());
            p.setCategory(category.getSelectedItem().toString());
            Store.addProduct(p);
            setTableValues();
            
            
            
        }
        else{
        JOptionPane.showMessageDialog(null,"Enter The Details");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        new Dashboard_org().setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (!searchBar.getText().isEmpty()) {
           Product obj =Store.searchName(searchBar.getText());
            if (obj!=null) {
               this.setSingleTableValue(obj);
            }
            else{
            JOptionPane.showMessageDialog(null, "Product"+(nameItem)+"Not Found");
            }
           
        }
        else{
        JOptionPane.showMessageDialog(null, "Enter The Name");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
       prd_ID.setText(model.getValueAt(index, 0).toString());
       nameItem.setText(model.getValueAt(index,1).toString());
       category.setSelectedItem(model.getValueAt(index, 2).toString());
       stock.setText(model.getValueAt(index, 3).toString());
       wsRate.setText(model.getValueAt(index, 4).toString());
       retailP.setText(model.getValueAt(index, 5).toString());
       
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (!prd_ID.getText().isEmpty()
            &&!category.getSelectedItem().toString().isEmpty()
               &&!wsRate.getText().isEmpty() 
                &&!retailP.getText().isEmpty()
                &&!nameItem.getText().isEmpty()
                &&!stock.getText().isEmpty()){
            Product p = new Product();
              p.setId(Integer.parseInt(prd_ID.getText()));
            p.setRetailp(Double.parseDouble(retailP.getText()));
            p.setWsr(Double.parseDouble(wsRate.getText()));
            p.setStock(Integer.parseInt(stock.getText()));
            p.setName(nameItem.getText());
            p.setCategory(category.getSelectedItem().toString());
            Store.removeProducts(p);
            this.setTableValues();
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (!prd_ID.getText().isEmpty()
            &&!category.getSelectedItem().toString().isEmpty()
               &&!wsRate.getText().isEmpty() 
                &&!retailP.getText().isEmpty()
                &&!nameItem.getText().isEmpty()
                &&!stock.getText().isEmpty()){
            Product p = new Product();
              p.setId(Integer.parseInt(prd_ID.getText()));
            p.setRetailp(Double.parseDouble(retailP.getText()));
            p.setWsr(Double.parseDouble(wsRate.getText()));
            p.setStock(Integer.parseInt(stock.getText()));
            p.setName(nameItem.getText());
            p.setCategory(category.getSelectedItem().toString());
            Store.updateProducts(p.getId(),p);
            this.setTableValues();
         }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Portal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameItem;
    private javax.swing.JTextField prd_ID;
    private javax.swing.JTextField retailP;
    private javax.swing.JTextField searchBar;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField wsRate;
    // End of variables declaration//GEN-END:variables
}
